### ISSUE TITLE
[BUG] - camera working with homebridge-camera-ffmpeg but not with homebridge-dafang

### ISSUE THREAD

**Issue by divemasterjm** [sahilchaddha/homebridge-dafang#18]
**Describe the bug**
i've installed both plugins, i can see video on FFmpeg plugin but not in dafang plugin, 
with dafang plugin i can control camera, snapshot, but not streaming with with camera-ffmpeg works

**Comment by divemasterjm** [comment]
solved "with audio: false"

**Comment by mkormendy** [comment]
Where did you configure this?
