### ISSUE TITLE
MQTT Pan Tilt Problem. Motor moves 2 times.

### ISSUE THREAD

**Issue by renedivx** [sahilchaddha/homebridge-dafang#24]
Hello,
 thanks for the great plugin. works fine. But i have a small probem.
If i press over mqtt turn left, turn right, turn down or turn up the motor moves two steps. if i send press the button on dafang site the motor moves only one step.

can i add something to the config.json that the motor also with mqtt only make 1 move. press button = one move lfet or so on

thanks
best regards rene

**Comment by mkormendy** [comment]
Having the same issue here as well.

**Comment by Zaphor88** [comment]
Me to.

**Comment by Hussamfhaily** [comment]
hi, you can edit the file moveCamera.js and delete line 30. Then you will get 1 move.

**Comment by Zaphor88** [comment]
Great it worked! Thx

**Comment by mkormendy** [comment]
@sahilchaddha If the the pull request I have made is accepted, this ticket can be closed. See my commit comment as the reason for removing this from the homebridge module.

**Comment by sahilchaddha** [comment]
Thanks @mkormendy. Allow me some time to release a new version on npm and close this issue.

**Comment by mkormendy** [comment]
I use release-it. It’s a super great way to release to github and npm all in one operation. Just `npm install release-it`, it installs a command line tool which you can configure. Docs on npm or it’s own github page too.

**Comment by sahilchaddha** [comment]
Thanks for the suggesion @mkormendy . I will surely implement it. For now you can update to version `1.4.4`.
