### ISSUE TITLE
[BUG] - Volume Control in Video Stream doenst work.

### ISSUE THREAD

**Issue by renedivx** [sahilchaddha/homebridge-dafang#26]
If i start the video stream in HomeApp. I can see the live video and get the audio sound. But the volume control i see below the stream doesnt work or change the volume. Any solution for this?
Thats my alst problem. all other works now fine.

Thanks
best regards rene

**Comment by iwonder-1618** [comment]
Hey @renedivx , The Volume Control on HomeApp is not compatible with Dafang as of yet. Its WIP. You can use your iOS Device Volume for now.

**Comment by renedivx** [comment]
Thanks for your fast reply. Ok good to know. Yes i use than iOS Device Volume. Thanks for your help. best regards rene
