### ISSUE TITLE
Homekit stream not responding

### ISSUE THREAD

**Issue by TylerD89** [sahilchaddha/homebridge-dafang#30]
My configuration is correct. I have a locally set up MQTT and have my rtsp address pointed to the correct IP address, but the live stream won't respond

**Comment by sahilchaddha** [comment]
Live stream is not related with MQTT. Can you play the stream on VLC ? @TylerD89

**Comment by TylerD89** [comment]
Thanks for your response, but I figured it out. The FFMPEG library wasn’t working right (and still doesn’t work with the microphone audio). User error as usual
