### ISSUE TITLE
Homekit Switches not working

### ISSUE THREAD

**Issue by lay55** [sahilchaddha/homebridge-dafang#31]
The HomeKit switches do not seem to work. I have set up the "Capture Image, Night Vision, Restart Cam, Record Video, Horizontal Left, etc" switches in my configuration but they don't seem to work. 

This is my config:

{
                    "cameraName": "Front Entrance Cam",
                    "cameraRTSPStreamUrl": "rtsp://192.168.1.24:8554/unicast",
                    "mqttTopic": "myhome/WyzecamPanEntrance/#",
                    "disableStream": true,
                    "segmentLength": 120,
                    "maxDirSize": 28672,
                    "recordingFilenameFormat": "HH-mm-ss-D-M-YYYY",
                    "checkStorageSizeInterval": 300,
                    "folder": "/Users/Lay/Movies/Cameras",
                    "accessories": [
                        {
                            "name": "Front Entrance Motion",
                            "type": "richMotionSensor",
                            "threshold": 82000
                        },
                        {
                            "name": "Night Vision Switch Front Entrance",
                            "type": "nightVisionSwitch"
                        },
                        {
                            "name": "Record Video Front Entrance",
                            "type": "recordVideo"
                        },
                        {
                            "name": "Capture Image Front Entrance",
                            "type": "captureImage"
                        },
                        {
                            "name": "Restart Front Entrance Camera",
                            "type": "restartSwitch"
                        },
                        {
                            "name": "Motion Tracking Front Entrance Camera",
                            "type": "autoMotionTrackingSwitch"
                        },
                        {
                            "name": "Horizontal Left",
                            "type": "moveCamera",
                            "axis": "horizontal",
                            "direction": "left"
                        },
                        {
                            "name": "Horizontal Right",
                            "type": "moveCamera",
                            "axis": "horizontal",
                            "direction": "right"
                        },
                        {
                            "name": "Vertical Up",
                            "type": "moveCamera",
                            "axis": "vertical",
                            "direction": "up"
                        },
                        {
                            "name": "Vertical Down",
                            "type": "moveCamera",
                            "axis": "vertical",
                            "direction": "down"
                        },
                        {
                            "name": "Recalibrate Motor",
                            "type": "recalibrateSwitch"
                        }
                    ]
}

When I press either of the switches in the home app, the MQTT server does register the request but nothing happens. The below screenshot shows this
![Screenshot 2019-05-08 at 6 54 14 PM](https://user-images.githubusercontent.com/43588663/57378590-b8d3e780-71c2-11e9-8417-834a202a44a5.png)

Kindly help

**Comment by sahilchaddha** [comment]
@lay55  Is homebridge-dafang hosting its own MQTT Server instance ?
Can share full plugin config & mqtt-conf ?

**Comment by lay55** [comment]
@sahilchaddha Hi,

Its hosting its own MQTT. Anyways it has started working now. I have to restart home bridge every few days though to make it work
