### ISSUE TITLE
[BUG] - Rich Notifications Don't Work On iOS 13

### ISSUE THREAD

**Issue by tarbychark** [sahilchaddha/homebridge-dafang#36]
**Describe the bug**

Since upgrading to the iOS 13 betas, motion sensor notifications no longer include still images from the camera in a room as a rich notification. This has persisted from beta 1-6. 

Home hubs are Apple TV HD / Apple TV 4k, both running tvOS13 Beta 6.

**Expected behavior**

On iOS 12.x, when notifications were enabled for motion sensors, it would include a still image from the camera in the room as a rich notification.

**Config**

{
            "platform": "Dafang",
            "mqtt": {
                "hostBroker": true,
                "port": 1883,
                "host": "localhost",
                "debug": false,
                "mongoUrl": "mongodb://localhost:27017/mqtt"
            },
            "cameras": [
                {
                    "cameraName": "Kitchen Camera",
                    "cameraRTSPStreamUrl": "rtsp://address/unicast",
                    "mqttTopic": "Name/KitchenCamera/#",
                    "folder": "/Users/name/Documents/Camera/Recordings",
                    "accessories": [
                        {
                            "name": "Kitchen Motion Sensor",
                            "type": "richMotionSensor",
                            "threshold": 200000
                        },
                        {
                            "name": "Kitchen Auto Motion Tracking Switch",
                            "type": "autoMotionTrackingSwitch"
                        },
                        {
                            "name": "Kitchen Night Vision Sensor",
                            "type": "nightVisionSensor",
                            "threshold": 0
                        },
                        {
                            "name": "Kitchen Night Vision Switch",
                            "type": "nightVisionSwitch"
                        },
                        {
                            "name": "Kitchen Auto Night Vision Switch",
                            "type": "autoNightVisionSwitch"
                        },
                        {
                            "name": "Kitchen Record Video",
                            "type": "recordVideo"
                        },
                        {
                            "name": "Kitchen Record Audio",
                            "type": "recordAudio"
                        },
                        {
                            "name": "Kitchen Capture Image",
                            "type": "captureImage"
                        },
                        {
                            "name": "Kitchen Reset Streaming",
                            "type": "resetFFMPEG"
                        },
                        {
                            "name": "Kitchen Camera Brightness",
                            "type": "brightness"
                        }
                    ],
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://address/unicast",
                        "stillImageSource": "-rtsp_transport tcp -i rtsp://address/unicast -vframes 1 -r 1",
                        "maxStreams": 5,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 25,
                        "vcodec": "h264",
                        "packetSize": 752,
                        "maxBitrate": 512,
                        "debug": true,
                        "audio": false,
                        "additionalCommandline": "-x264-params \"intra-refresh=1:bframes=0\""
                    }
                },

**Logs**

I didn't enabled debugging, as it appears this issue is on the iOS side of things. My Mac mini currently running 10.14.6 still receives images in motion sensor notifications, as well as my wife's iPhone running iOS 12.4.

**Desktop (please complete the following information):**
 - macOS 10.14.6
 - Node Version 6.9.0

**Comment by tarbychark** [comment]
Is there any way to bind the motion sensor component to the camera itself? It appears this is the only way rich notifications work now in both iOS 13 and Catalina.

**Comment by ScharV** [comment]
I‘ve got the same Problem. Is there already a Future Solution?

**Comment by tarbychark** [comment]
Looks like the camera-ffmpeg folks are working on it

https://github.com/KhaosT/homebridge-camera-ffmpeg/issues/332

**Comment by ScharV** [comment]
I think this could work :
https://github.com/NorthernMan54/homebridge-camera-ffmpeg/commit/a29948e21ffdecbb8ab99d46a0c6f5123fd6fc7c#diff-168726dbe96b3ce427e7fedce31bb0bc

Bit have no idea where to implement in this Plugin

**Comment by joemulray** [comment]
+1

**Comment by sahilchaddha** [comment]
Kindly update the plugin to v1.5.1
