### ISSUE TITLE
Rich Motion Sensor not working

### ISSUE THREAD

**Issue by sedony23** [sahilchaddha/homebridge-dafang#7]
Hi there,

I can't get the rich motion sensor to work. Motion is detected, I get a notification however without the preview image...

On the Dafang I have the following enabled:

MQTT Status Server
MQTT Control Server
Motion - Snapshots
Motion Detection
Motion - MQTT Message
Motion - MQTT Snapshot

The MQTT part for everything else is working fine. I also get a Snapshot image saved to the SD card (which is probably necessary).

Is there anything else I am missing? Do I need your firmware mod version (I am currently running the most recent one from EliasKotlyar/Xiaomi-Dafang-Hacks)? Any suggestions?

Thanks for this awesome hombridge integration!

**Comment by sahilchaddha** [comment]
Hey @sedony23 ,

Try moving your camera and your richMotionSensor in the same room in Home App. Let us know if that works for you.

Also you dont need to enable `Motion - Snapshots` to work. The image in notification is live snapshot from the feed of the camera.

**Comment by sahilchaddha** [comment]
I would recommend disabling `Motion - Snapshots`. It will fill up your SD card pretty soon. You can try Capture Image Accessory from the plugin. It will store images on your homebridge device instead of camera SD card.

**Comment by sedony23** [comment]
Awesome, moving both to the same room did the trick! Thanks for the quick help! Great :)

**Comment by lemar89** [comment]
I have same problem, no image in notification. Camera an rich sensor in same room. @sahilchaddha can you advise how to debug issue?
